import { generateSessionCode, validateSessionCode } from './session-code.util';

describe('Session Code Utilities', () => {
  describe('generateSessionCode', () => {
    it('should generate a 6-character code', () => {
      const code = generateSessionCode();
      expect(code.length).toBe(6);
    });

    it('should generate code with only uppercase letters and numbers', () => {
      const code = generateSessionCode();
      expect(code).toMatch(/^[A-Z0-9]{6}$/);
    });

    it('should generate different codes on multiple calls', () => {
      const codes = new Set<string>();
      for (let i = 0; i < 100; i++) {
        codes.add(generateSessionCode());
      }
      // With 36^6 possible combinations, we should get at least 95 unique codes in 100 attempts
      expect(codes.size).toBeGreaterThan(95);
    });

    it('should only use characters from the allowed set', () => {
      const allowedChars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
      const code = generateSessionCode();
      for (const char of code) {
        expect(allowedChars).toContain(char);
      }
    });
  });

  describe('validateSessionCode', () => {
    it('should return true for valid 6-character uppercase alphanumeric codes', () => {
      expect(validateSessionCode('ABC123')).toBe(true);
      expect(validateSessionCode('ZZZZZZ')).toBe(true);
      expect(validateSessionCode('000000')).toBe(true);
      expect(validateSessionCode('A1B2C3')).toBe(true);
    });

    it('should return false for codes with lowercase letters', () => {
      expect(validateSessionCode('abc123')).toBe(false);
      expect(validateSessionCode('AbC123')).toBe(false);
    });

    it('should return false for codes shorter than 6 characters', () => {
      expect(validateSessionCode('ABC12')).toBe(false);
      expect(validateSessionCode('A')).toBe(false);
      expect(validateSessionCode('')).toBe(false);
    });

    it('should return false for codes longer than 6 characters', () => {
      expect(validateSessionCode('ABC1234')).toBe(false);
      expect(validateSessionCode('ABCDEFG')).toBe(false);
    });

    it('should return false for codes with special characters', () => {
      expect(validateSessionCode('ABC-12')).toBe(false);
      expect(validateSessionCode('ABC_12')).toBe(false);
      expect(validateSessionCode('ABC 12')).toBe(false);
      expect(validateSessionCode('ABC!12')).toBe(false);
    });

    it('should return false for null or undefined', () => {
      expect(validateSessionCode(null as any)).toBe(false);
      expect(validateSessionCode(undefined as any)).toBe(false);
    });

    it('should validate codes generated by generateSessionCode', () => {
      for (let i = 0; i < 50; i++) {
        const code = generateSessionCode();
        expect(validateSessionCode(code)).toBe(true);
      }
    });
  });
});
